# Generated by Django 5.2.16 on 2026-07-21 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_name', models.CharField(max_length=100)),
                ('groom_name', models.CharField(max_length=100)),
                ('wedding_date', models.DateField()),
                ('ceremony_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('about', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='weddings/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wedding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wedding',
                'verbose_name_plural': 'Weddings',
                'ordering': ['wedding_date'],
            },
        ),
    ]
