# Generated by Django 5.2.16 on 2026-07-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wedding',
            options={'ordering': ['wedding_date']},
        ),
        migrations.AddField(
            model_name='wedding',
            name='ceremony_time',
            field=models.TimeField(default='16:00:00'),
        ),
        migrations.AddField(
            model_name='wedding',
            name='instagram_hashtag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='wedding',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='pix_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wedding',
            name='primary_color',
            field=models.CharField(default='#C8A97E', max_length=7),
        ),
        migrations.AddField(
            model_name='wedding',
            name='reception_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wedding',
            name='secondary_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='wedding',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='title',
            field=models.CharField(default='Meu Casamento', max_length=150),
        ),
    ]
