# Generated by Django 5.2.16 on 2026-07-21 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wedding', '0002_alter_wedding_options_wedding_ceremony_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('invitation_code', models.CharField(max_length=20, unique=True)),
                ('companions', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('DECLINED', 'Recusado')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='wedding.wedding')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
