# Generated by Django 5.2.16 on 2026-08-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_confirmed_at_guest_message_alter_guest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
